language: java
env:
  global:
    - secure: "kmeW7xxF7l8DoYE2Ax9LQWH8Yv8Kb8HnZVZ2wKgaOp+yVVAD5eZNV2GpIFOaB+bp6M+jKQ8I4U82XMzqEVOr5FMdFLCDoukbZ1IDXKaN8VT9Ai4P6uO+gDjW92hSmKwL2EZ+yYWEg8sF/OHdjjeQndRTUoQMgl2dYsk8fLc+VaAbF7wcNV5oSh3tsx0dia5IWL6vcv0C1BJb71U8v44pfWl0zMb2AE3WRllgcexpzqOB2caW0cuDgNkF11/DvloyKx5zIC4xGfHED8dDAoJm2RU7wYfNqS64hau/SbVO5MEaJJERDaygq7WRDItYMkK6IAvjfExd4a76GYcZ4nqEO7Up79RciMIMwrZKLvdihTLOHT/4n5grRLP6UoVbIe9V1r2ARBcp3tV2utw9zz1iaMCcBxe+xju1nD63g7FGFsef13jKiZz+hKutK3i6eq4/OjLD7iZayHG8aOsr8Y9N6IqWCxgzeTZ1AQ05lieBVxKOwmR/n2N54uQU5EZvEyD9uTW+CSBugkNNwZH6/C3kJ+RKOkKsvT/+Vn4pYH6NS20wQ1TSxBJJ96dQBspjgV6Oy9jkwC+tauWgM1KSu1CklHLr1OTbl6lRWaJqmfP7DGXxRtNSfXged06s/i88LNM32sz6zaYaN0zNC/wpuur7c6+zch38HexFnh9iFlqcFQw="
    - secure: "uJEQJHOEIDoWH25zHM1y76CQ2ljgMYzvg1jZ6p2fUN7SkkL0+Ta0/PxpPIe5jW+aJhwOx6IaCYr1UCJBGNv5L7siWOsH676K0cNoQewPpCIDCREfw5POHd5EpVHXATCPIpVhX+lG8N6Oc3uZaqfCB9ZFvkSkUktOXAreqjTpEmrKEBWe7tc0ycbY6dypJrS1xUbLdh6Y30AjQiSrA5pqk0F52ygSzUbja/yMr4D1xd1az5Ia6PtHPJhq0N5adTpurutTFI1HdT4ExXQkNyRtPGlU6lVxKxqXjoEmi0xe2QTQa+caD0aIq82CPbW1woiKwKqA6EzEz2k0rUzS7UVA9XUlsd2WhOUc0H6EnisruK6lA4uotWfuI+MDOSlBya3GKKQvu2lGjXvxlXXEKnAe+j/GVEp6ykFP1ujr74Hwf1j4Et0WnL2pKmkF1ETuWBCVaDPccIFgnZtw/jjEVN0EFbzxwb92bKR/FVkmMhHHgfLp2t3FR5XtP4LxtTktfIrsRV8o7o0mOWvgPUnTZ33Etu1IxXgwmX2KsRsONeh+Dk2W1qi8R/4cNq17KKmCx4QxjFUxAlkK1wpzX8NRXvhvvWAwL1UxoQdwGkzc1ePUfQUWTHHyQcvbvBttKYnLu5tl/oEMrZ3AG1/0Nyl3QsjYrHMRAAgtM7z1mqMbC2LdS+c="
    - secure: "vylWEvfgT/9h6fFwEs8uWCkHrojRAkAk1cWoIeI0iSoH2hgBQS+upk7cZ9nog5cjQGPooEP4TMHQCsY8rSqf5wvFdrvipBAwMphptELZ30z533t8Bx44ZMoXz7jmwC1l3u6I/owFaSShrqYEQC2HWIzGAS/o3alPdJxoNQhl589oVlTRuimBweCW4wrTT0tclW7gEMZIuQjVIFA1XJJHzRJpvtFg8P3IOUPjyUNOFVYqUW/qnjWtO1wXtq4bq5ycpn2amEW/h8Al84DPYBHvm/LALPTgv1ggHtVm94cwZ9AplmESTkQkZWQnHGyXlJNeRmsQGpSmV5YiboqifIUAw6xllu9uvl1RzXtU00OzstE7eAJCQ1i17zl5dJ8Hexmo6AJrO7LaRXp33L6Ng84pK9xL+viNmFhhRk5X1oFyGf4UBefIayLqYj7NVOzmPnuFbSNiqQxiDH+S1GF4FxxB0465aSsF+FEh9lArOH92NpOJR91EbIxWhbhvpAzjGxBBRm6dmWR1hUETvAf/vkBSmq8WQfNQsIVYfHb8gBPtreKMUda+KDG3eKpLVeqrIKuZpuo5F/0cVANG5pJa24WSd1xOnwGl8YG8Ykp1t+bSe0JQ8GRo72SIGZT+IEKxikCBCxt2bQWdV0D/c5zoEgEN0+ukl9bj72NfjetEHZEcB5g="
    - secure: "nwHEfV8bvFq7gncjoJ4Ys1qG/HeY0I3ngI9ny1gheT33E8BrdFd19X7CzOC3fUPKbDZjIiZBrgMkrijZ3ROKBTWR3c1qCpS5q2IUSl6oOoO15sQXbTyofaa2ruN4cl76yC5/jlXHyJZozoBqtPE+p1UmQopvN2xEGODlDNkdGy4kpDvZIOo5MIGteYtbiqFCIMqR2lAYp7DeWWPTBZCLSFg9/EtRwseMVn0tXHHp9/D/Et8JlFD23t92JQkMNgobjqUcEiDzv0gAQRqmS3C5R6TrpZOy24yMIUawkdPGtjcLKKPEji+VBLElETpyvIxo4SaZAlJmUUVzSR3WR+fpq/E0Je3icZNcxHUkN3VNar7rfysacvpvJ2tw3S2oIOPa9am/o1td26hA1A6SknUnqirLGqFkur0Xucyi+Fs0J54/OZwyGp54d9xaZF9so7pf+lyT5yfWnqoyo7AzQCgRHLcP3ufDVxSWBRp6zUUX4peT0eGR+K2ru47yWATDUX1NCsXh2Z8SnxJ2vZxH3cFnRaEoSN3uGxQGLU1VazVegwmabBm6klxEhBxZ4GuyOba3qWWzxwAGNM9auAe6WYcGZcTANOXD/zY/TKeknVzdaSoX7qoG6HYu3hTUjMT9rsxR0wMwwaIBxnB9XK0ZiDwjsxlVB4pUCsVXQt67Bszt+S8="

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn verify && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
      branch: develop
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
