language: java
env:
  global:
    - secure: "h6IjCnqAjREuCdjvSOE/HklciL+MjFsdIT5o0GPkwT+pdJiZfH5URWja2p4wOq4aHlPhfSU98UnkEijriUL6erheCZrW8gfzVojZLnT76As/TJqlV0d4w7u4SZnpNofX98LTMx+rpKYrZB+x3yt+1od+qZbDdSl99fTCMeFyNZ+WTymJ5I9mXKazFnFkZRaHMDfcXB0TDlFee7XeXAJNCzWLRwZSlf/gf+v0/BpCw+9h2/58h/UVXKeRTCRuhe1PNiHfmn3llChP/C7huoM1CIQJVKm1DWcl1sTCkAMErNOl4W7b3Vzt2PRR/86VZ1gAV9sBMfSUATpNiOmLQ9qknXLJJrd9E6vmXtCLP3wNPhjUEYn2EHafeVsoL0TvLtUbthWSdCxHUWe9CS8MrbHDwQAy+riOyw/WFGfrXHtC446/qQnG7JtMDJkA0NKgVFhqupO5Et1JliP43pB9SmQDkRaoqoxO37oUKsDuocM/PL0yBSp6TjLcsYYujP4j2TEB4uY4XTq9Irgm/4W3FIFhW7yllTTPKgVSUD2UZm3Ip46TpEJHcxrJPo0RXnMvBBwGoUN0GY3zVOjEhUl17khP5gIXSCXciKJjIHgQC5p4MjzK+G8mVg3NpugBf4CTZ/c6tHuABdm+QirpLP0mmkcwXOGOo3l8XpPVHTOviKtYvm4="
    - secure: "vYDMR7Nd0S/5sI9f2G+4Vh/OAMjZuclCa/RXD7IPH5iQJbSvKnoXhNSXjP2wILwgTi1s5Icv9gTisgDzxZSfGuH2RNG+Aew627mbBx57se7AVejCJ2bGFAQrO2quEZcotOsHYFFR42W5bmcG8Qg5i9E1Gs51YNeuu6c5w2mxuDDSRdcfY70nJti2/Fw7B0kBI5c5CCo3BAbBgBOBXLJZ+WqGdO1BDmhPlBbGBAvnSdB8VSdOL34+TYKytATJ6BeMR3UcF5J06yE4tZyXR9n0DBTxw8FDmuam1ebnyoMTpRdiPEamo3OQZtBMtPRE2C3UFhwg4Iq9OpxxJXqhhEw2qh7S7a3DpXobT02FUJLqlfktfdx8CRR4JuyT5X1S/5pSueOBCvYkzbI7aYLS+D7LPJj4ayUKq4sYKDx+5QUiXK7FUg3H38Gn509H97OyOgxbW7qXAAo1vh6TPXyxBJgabtxQztMJo2nBfy6KLRbom035tG1R103ZKwqnGRkUBMn5KKeVMwVUl56TmVmqi/0iE7dqXbU3Z8J9vtP04ijPd2pozRRxcT3QgIo/xrbwSPaoxcJNZkYkVkmThyDB1IpSpTM1oaM8Va0KKOYE74yQSmTqR1PSrMNmzDLFU5W8Qc1x7NO+hc4MVdwxDPb0KD6opxvEMjRwhOm7JpKzHHe9nSs="
    - secure: "LAASqDr2QCvXEl7F3IIz0475Sgcqs1VihY4ot0xVKHCJSxas7OMbfuGYKP7iqSHQQhckFeM4Dk5OmLwnaTNuzGVaqK/gLNUxdxTN9QUpwsFF01ZYW35KD02TbCXrLEHFncRg3JJzWY1DZMgsBDDk6cb+zfXTvw41d9//2W9rq1TjTsWI4uKoG5dQAhcaVyJZLMu63JZ+PB/gHauUKu1rGzIIBD8D4rPT2Uj+/QkWbgnqm/Ef9sjCTpGMoW+Q9hlXzOgEEnU7yL+yIkjni+XiYMywNjo5OLWzkLDXSQkbNeaRrsfWK5KVM45zfirr+Yn3Q8b2u65lJMZo3uSd+q+tooTZtf4MHNLe+0Yd1UruEhBa4BMWeLs+HZaSG1o0menEo2YiMl1T/cDiGZ9x/5+9m0WJ6IxHK3I8vI4T7dK3DXyDT1Q2lkfi4JCxsHwv7HLKvbwKyIHskGI8nmW9QrwtuqQtfDXxPhvyp/6l6VWQLKgj+wDnMhykHZ19kz+cN8u5/tS7+X0hrFyhLQPdGa8CeSQ1FfcbQZuF6DiaHTH/U14GvGxHXpRKBU6d2IXHMVkUktU8/bZBeNy5bnfmQInDfCYO1I/aQX6cF/cv3Pqpz5ZaaKlOaeU7oQd+vefr3YGqLif6t/RRxU5tTuh6y8EL/CVvTMKjUG+K3KvQHOd7UsA="
    - secure: "TQZpT0z+eCHLLtylIImhpSXQZxgn3HBRjUbZyHSgi+r047fgRufmihlueNzNUTKYogA1rP6Mtos1QBkVr0eiM1DRZg+VURnL+rnOOtp1qa59vsSo3+IjWO/+a3KHnMcg8v+Y9mJ+cAyFwFR+ETWgPnyBHXA5hoPGD86j26mhbWqMM46OWLMc7MGB47Jxxe2K+yVe/7xdLVfX2B47k17J5xiWEbxrVmsl3NjryV4L6xhVtnJJk/6bJawKqBrD2EsPgPnIxDSUnAVi17UqUPevlt6GyZKtCmd9Sn5X8/p7qFXfFrkYOGdp+LkPD1+k/WjLTb6EIcxOgBGE7/+zkElWsjNcRp8ez/Q82vzlwLwUh7GHEs1TtEr372lzE8f9I6suzOkLgzAZmf5mt05P47mjNwBAL2coOTbj5PkFcAaDIG4K4+I8cafKUM1KSx1jWPATRaXnBCWt5IWWTcCIFJJlqg6rNC5SqMlLNDQzG9prXCspp+pxddavxf9/bb62o6SMnGW499Aj8Q14YrTf/nr346kmuxByWvj6JnZgzwTw6EGabfmo/IOHVeTbC9Ropyj88e2tdWHkgdAQ3c7lxkvQLPbMnWi+qaAuKUrQNmWGJtO28G6ulZvWs12k7dlkcUgElrWNyER/ohpd2jA4fbR5SpWDf6w/YT/vdi5KEuZLOf0="

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn verify && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
      branch: master
