language: java
env:
  global:
    - secure: "cytH1MDyRMtYRAai8gESBznBDNaHuKJMMX5kkdlRxkvKlbbZMuB9BlEXQdToPCRvjSBGkUYTnwhkWfOoTIp7ylQABm2/8D49vJXReQvMLuiFcqQQFB9lQcWLhXbUZ2nr4dIRIsDGfA2znck2jVuLKkf72+FHL0vtrxYtyXHDVwBvgH6ms3WyKQKZ7On8Ard2z2vlt3F21GbP/pQk1dry8LO1SXLLvxDej9TtLvZUqp6KA1rcW/foOX1MQyMsr4W6K7OH60I+GF0ts9qdYhkIYGIrcBMWQrsqnbBOCJmQDFcuxgxOPcodohYHB7W0N4TuPjA3AXMSKhqJ1Ul/NEaf5YaPETkRFFrLc0ZGjRG1Ahn/+pEhU+2S6TdBSk0a3lKelmJxBZA6I1C+JGUYoj35tbE0MF1p1dn1wdba83xg/za3oUa/X7qV3yRt/n2hiorF6XqxfZz24Ooy0wZGTskxp49Noejfh4GT7P9+gS9XQkgofZskx4qBhV+cSFj8RkkjXeia+yRFiZUASCNfZsQsyOoN3vtKhm4ZlMbPWNZ05YvVaqMJgYRFZe8lgvmJ6ILm8jFwfSXDd3nuwLJJPU66DVdizrS3ao9JBqpD0MkBp/bweECu63vg7WgoT/nXqsFc5Jt7dwuTJSFOsJq5cs2sGaR9G1/e7xXKS3XtYQMOk+o="
    - secure: "mn7bMhQ6VaTTw+Zqp8TVlqSbJQONTekiA/07XPWs9LDt1lGfnlatxF6pPXWKwh5yjWV5W1JWpV3oVd1L5eoArJkstlO+8I1ofIEdiv9YRNXJ/99rODw6v2bvLKtaikmC/FwruAoP7m+vIX2NvxpbY9AR0iwq4drG4M+ADCRqg0+XcJzHXFh7qCZLai5KHt0IKbLEp/n+o7daEbR/T8+qcpL7J6//cwgwI/TKt0r4yRKG23UHr6afDtSLN6ZyiB5foruaBGqaW2o4ITWySIAYWOyvxRW+upmlCTNw+MfA5eT+4xDnB1Az/AzowZ2uyEstpi2amjNB2OuitvclDBfVXj/EAJZsQWGEHafz+AUPDsSkbyTX0m28OAHgr9pTImwBnRRP76Rm3wKzgAxJHhMICExcrWLDaMHsym8sd1pv1k+lakpscR4nIi8RWhxAL3NcQN/rG7WeMffOX1Rt4DDpwvl9JYoLCHVd5PAiUCPkOf0fHF8SHbJDUx9zqcWjlrBuzcCm66I+EEq3Rz3ePRLiNkUVkjdmY0oRIi405wlaiKEHYJqMBg839d5PQYRo+CjGnLd9OCTmzh123SOTTXYQ1/7zIOaaMjzfambCO9BuqajWqemQcnxAzsz8fNLydCnnRoCyTyJUHiJ0qfIu/BaqhMWu0iJ2DfNj/Mta2AlWS4s="
    - secure: "E6/SnQSGrLNukOM3CNj6B/m9KYkALVcD04nj4r+RX5tLnLru1Urt5B/JptOaj72P6D8u+NzTG4wZv967MGfM/uAih/e8E17yJfT0lG27le/ZmdUWbfsNBulKFkmlChZLTQpOWi6VQ+g5JMPC+RSdJC3SlmEwR6vwVZAhZevN+JqdSxUrmZVWg/q/YXdQ4rqRsxJaq5HQmYtn1DV5EsY4TKWuZ3hVTYZy3vPHadJjh9BKE85J+ZtIAvi+g+aJNX2+7uzQp1I4zW4gqNJ4/Td0z2T4sWNwO0RRLJFYv3pxkZVJA9w5Poz1sNOHTaFyaxmU8GgOA7wCpUmrBiaAqpRR7exXxHLQ5xdDKocpQQ2XmSZWmiXzNp3n7FqpXoQ85Ik2LfMxhfH2D0RJInPHcwjPlh4qpX3zKp7c9IM37fBdX42K0SutDKd4knqfwg5Ip90trxZd8A4BN3dvbOK3hLtsRY/3Y7J3BzG/x5PqKmbD8MbWRkg/PdhpdrsS6Rl/MeMJtM9uxvKXBmZpad3CauB5fQ9nxurAm2VfakgxWXJbW7JVuH2e4MZKAPb5COt4DaNEIE4nBVMyPrGoPQaRs53sjxvbkE2IPQEKygHJHD3hYynQNr2FDq6kQNGgh34uv7CSyf5K7RFZ5Yn+XbRabhLIDTBqO5qxogaFpUVenmKBTs4="
    - secure: "O597FyHp4Qa4MQHz2nFJbYkWRD5EA/9MDeiE3hbmoQsy+0F8k31Di974/ujn2tHNQUIYI8Yw8iARKltfr73fLF8DUWVXcyqzJ9eEpo81EtjAQX1ZR3CunmT9ZX1bf9TRf26BOSv1KQm+Y7P+gmQn75Z2OiHTvLyyUnprUun6ohkd+NQ4BGzXhHkGXJcQxRmpnVSBLjvk/K4y8M8K3Hc+HnXAGnzfgXFN8AruvJeaZeqlFiAiKT+HZK/WIB1zU7yECLMWg/IZR7W0vq+NqLJHofGdYE3DuzvFhClH8ts6U1SKAEWYBiXf/3tIJ5bH2AEmz+UTiuLsdKPd4JLpvN7NATPthkse1/VLmWobjHkOSv1DM2P9EzC1V59vifY9L/2vMxKBMAsCR51jsqv8+fr2VXuoQ9uZOHvS8Vh/4+CE2vZUSA23k6bJi7SjP8I+5xwnixZMPOkRN9W1q7956eQHYxVi8N/a793OeIgslixuK0NCgAhs7V6DFmEYCxzbQMg3S76eMquMtFn+HNflwdU5ZLH9WCVZFpMaWrZN4xH2zPavIuDIB8L0UbbYBaYupcGCRu8Hhb2DA2unwsTB7y0TyCPEM5DTbGoOuKwKAMxsotHu4/Qzd/GsmyBYVeCMQpq9PhQptKhI7x5vrYc8TWKeeOWMt34/y6NWrXxuTaz+VFc="

sudo: required

install: true

services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'

script:
- mvn verify && bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    on:
      branch: develop
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
